### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by visaoo** [retrouser955/discord-player-deezer#1]
I'm using:

```
node: 18+

"@discord-player/extractor": "^4.1.0",
"@discordjs/opus": "^0.9.0",
"@discordjs/voice": "^0.14.0",
"discord-player": "^6.0.0",
"discord-player-deezer": "^0.0.4",
"discord.js": "^14.7.1",
"ffmpeg-static": "^5.1.0",
"opusscript": "^0.0.8",
```

discord-player playerStart event displays track.resquestBy as null when I use discord-player-deezer extractor.

discord-player-deezer cannot play links deezer.page.link...

Example: https://deezer.page.link/JjYAgshEXYTMLFDR9

**Comment by retrouser955** [comment]
Hey! I don't think track.requestedBy is handled by extractors but yes the second issue is an extractor problem. It seems as though I forgot to validate Deezer share links as I already had regex for it in the source code! I will fix it soon.

**Comment by retrouser955** [comment]
Ah yes. requestedBy is indeed [handled by extractors](https://github.com/Androz2091/discord-player/blob/master/packages/extractor/src/extractors/YoutubeExtractor.ts#L80). Thanks for reporting again! I will fix it soon.

**Comment by retrouser955** [comment]
[Fixed](https://github.com/retrouser955/discord-player-deezer/commit/5c76901b2721b4a29386476af2d4d5240fb6694f)
